name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read # to fetch code (actions/checkout)
      packages: write # to push to ghcr.io

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            LuloDev/deluge-update-pmp
            ghcr.io/LuloDev/deluge-update-pmp

      - name: Build Base Docker Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.output.name }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha, scope=${{ github.ref_name }}
            type=gha, scope=${{ github.base_ref }}
          cache-to: type=gha, mode=max, scope=${{ github.ref_name }}
